when add to calendar, add with description (with artifiacts removed)
DormSoup/dormsoup pull request #38
Opened 2024-11-21 04:47 UTC by lad6558

Previously, when click on "add to calendar", it creates an event with no descriptions. This feature uses the email html to populate the event description. 

Implementation-wise, it copies the "removeArtifact" util function from the daemon repo in an attempt to remove extra htmls. It doesn't completely remove all the extra line breaks as great as the daemon does (the events on the shared google calendar have great descriptions), but because frontend only has access to `SerializableEvent` (i.e. without text) I feel like this is the easiest way we can do it without shifting the architecture too much.

2024-11-21 04:49 UTC, lad6558 commented
![image](https://github.com/user-attachments/assets/5b9079ca-b08c-4cd3-95ee-cb029c61b6d1)

2024-11-21 21:41 UTC, gabrc52 commented
From what I can tell, the functions you copied are designed for cleaning the *plaintext* version of an email, but you are sometimes calling that on the *HTML* version of an email.

Many Outlook emails seem to have something like this `<style type="text/css" style="display:none;"> P {margin-top:0;margin-bottom:0;} </style>`

and it seems like this style tag is getting added into the text

![image](https://github.com/user-attachments/assets/81ecc673-506a-4d6e-a302-b162a054e6fd)

and what you intended to do from the function names (such as removing redundant line breaks) isn't actually being done

Could you please test locally with a few example emails/events?

2024-11-21 21:45 UTC, gabrc52 requested changes
From what I can tell, the functions you copied are designed for cleaning the *plaintext* version of an email, but you are sometimes calling that on the *HTML* version of an email.

It seems like in practice, a lot of the emails here are actually HTML emails, not plaintext.

![image](https://github.com/user-attachments/assets/d46c3a07-bf33-4e8d-a799-340d373b88b8)

Many Outlook emails seem to have something like this `<style type="text/css" style="display:none;"> P {margin-top:0;margin-bottom:0;} </style>`

and it seems like this style tag is getting added into the text in the calendar

![image](https://github.com/user-attachments/assets/6c03762f-e342-45e7-bf95-b7331a60be4d)

and what you intended to do from the function names (such as removing redundant line breaks) isn't actually being done

Could you please test locally with a few example emails/events and make sure it works as intended?

2024-11-21 21:45 UTC, gabrc52 commented on app/util.ts
> +  const isLocation = isMITLocationTest.test(content);
It would be best to run the linter in a separate commit.

2024-11-21 21:45 UTC, gabrc52 commented on app/util.ts
> +  const start = input.indexOf(";base64,");
nit: use startKeyword here

2024-11-21 21:45 UTC, gabrc52 commented on app/util.ts
> +function removeBase64(input: string) {
Is this actually needed? Presumably the email has already been parsed and the email only contains the HTML.

2024-11-24 23:04 UTC, lad6558 commented
Hey Gabe, thanks for the constructive review and taking the effort to do local testing. I've used a better library to do html-to-text and tested on a few events with no problem. Would you like to re-review?

(the linter thing was applied automatically on save, so couldn't help with that)

2024-11-24 23:04 UTC, gabrc52 approved these changes

2024-11-24 23:51 UTC, merged